export class CreateWBSaleRecord {
  accountId              : number
  nmIdCreatedAt           : string
  date                   : string
  warehouseName          : string
  warehouseType          : string
  countryName            : string
  oblastOkrugName        : string
  regionName             : string
  supplierArticle        : string
  nmId                   : string 
  barcode                : string
  category               : string
  subject                : string
  brand                  : string
  techSize               : string
  incomeID               : string 
  isSupply               : boolean
  isRealization          : boolean
  totalPrice             : number
  discountPercent        : number
  spp                    : number
  paymentSaleAmount      : number
  forPay                 : number
  finishedPrice          : number
  priceWithDisc          : number
  saleID                 : string
  orderType              : string
  sticker                : string
  gNumber                : string
  srid                   : string
}